#!/bin/bash
################################################################
### Text automatically added by daps-utils calver-init ###
set -e
function incrementVersion {
    CALVER=$(date +"%y.%m.%d")
    CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
    PROJECT_ROOT=${PWD##*/}
    echo -n $CALVER.$CURRENT_BRANCH > ${PROJECT_ROOT}/VERSION
    git add ${PROJECT_ROOT}/VERSION
}
incrementVersion
################################################################
